### ISSUE TITLE
How could I  use this kext?

### ISSUE THREAD

**Issue by startpenghubingzhou** [slavaim/MacOSX-IOKit-Hooker#1]
Could this kext be used by some commands?

**Comment by slavaim** [comment]
There is no console application. Actually, this is not a big task to write it by copying existing code from the user mode daemon / service.

**Comment by startpenghubingzhou** [comment]
> There is no console application. Actually, this is not a big task to write it by copying existing code from the user mode daemon / service.

In other words, it means that I should write a user-client app to use it. Could I understand in this way?

**Comment by slavaim** [comment]
Correct. You need a console application. Caveat, don't invest too much in this as it it will unlikely work on Apple Silicon, or at least it will be impractical to deploy this kext to clients.

**Comment by startpenghubingzhou** [comment]
> Correct. You need a console application. Caveat, don't invest too much in this as it it will unlikely work on Apple Silicon, or at least it will be impractical to deploy this kext to clients.

Ic. Now I think I have had my answer so I 'll close this issue. Thx again!
